### ISSUE TITLE
More extension methods for NDArrays based on Apache Commons Math matrices.

### ISSUE THREAD

**Issue by occultus73** [Kotlin/multik#18]
In response to the positive feedback I got from sharing the previous batch of extension methods I wrote to work with Multik, I thought I'd share another batch of such methods I wrote for Multik, in order to help me extract advanced linear algebra functionality from Apache Commons Maths. Namely:

1. Matrix inversion, which required QR Decomposition and Solver, and
2. Multivariate Normal Distribution random sampling, which required Eigen Decomposition and Solver - which in turn needs the TriDiagonal, Schur and Hessenberg transformers.

If you want to checkout my work, I've made a repo for it here - it's Multiplatform, JVM independent; see the common module:
https://github.com/occultus73/Multik-Apache-Math-Extension

Here's the extension methods spefically:
https://github.com/occultus73/Multik-Apache-Math-Extension/blob/master/common/src/commonMain/kotlin/org/jetbrains/kotlinx/multik/ndarray/data/NDArrayExtensions.kt

**Comment by devcrocod** [comment]
Thank you very much, you are making a really very useful contribution.

I will research your work shortly.

We didn't use Apache Commons Maths for three reasons:
1. For matrices, they store arrays as an array of arrays: `data[][]`. Since we store ndarray in a flat array, it is necessary to copy, which has a bad effect on performance and memory use.
2. For the rest of the methods, I thought that it would be too unnecessary to tighten such a library in Multik. This will double the size of the library, while not giving much in terms of capabilities, which is disproportionate.
3. We can implement many things from Apache Commons Maths ourselves.

I have roughly the following plan:
* I am now finishing reading and writing to csv files.
* Support npy format
* Support arm processors for multik-native / multik-default. That will allow these modules to be used in Android.
* Use more methods from Lapack. First of all, factorization methods.

We are also going to take an intern for the summer to implement methods from linear algebra in multik-jvm.

I will come back here when I look at your code and then we can discuss in detail.

**Comment by occultus73** [comment]
Yeah I definitely think you guys should implement the linear algebra functionality yourselves. If my code is pretty hacky and half-baked. If it's of any use at all, it's just as a sort of demonstration of how you might extract out the algorithm classes from common maths and make use of them in Multik. 

It's a straightforward, but cumbersome process of translating from Java and removing any JVM dependencies. Also it gets tricky where ACM uses one of its special implementations of Matrix like a Diagonal Matrix or a Block Matrix. This was the case with the QRSolver; I had to hack my way around that by pulling logic out of their Block Matrix and pasting it inline and simplifying the best I could.

To my knowledge, nobody has yet written these advanced linear algebra algorithms in Kotlin and published them anywhere, so what else is there to go on?

**Comment by occultus73** [comment]
You've merged my man Sergey's PR which provides most of these capabilities, so this can be ticked off.
