### ISSUE TITLE
Overload resolution ambiguity.

### ISSUE THREAD

**Issue by paccuk** [Kotlin/multik#201]
I have been learning kotlin for a few days.
When I use multik in Kotlin Notebook to create an array, I get "**Overload resolution ambiguity.**"

**Build Tool:** Gradle
**Gradle JVM:** 11.0.22
**IDE:** IntelliJ IDEA

Here is my code:

```kotlin
%use multik
val x = mk.arange<Float>(-10, 10, 0.25)
```
Line_21.jupyter.kts (1:12 - 18) Overload resolution ambiguity: 
```kotlin
public inline fun <reified T : Number> Multik.arange(start: Int, stop: Int, step: Double): D1Array<TypeVariable(T)> /* = NDArray<TypeVariable(T), D1> */ defined in org.jetbrains.kotlinx.multik.api
public inline fun <reified T : Number> Multik.arange(start: Int, stop: Int, step: Double): D1Array<TypeVariable(T)> /* = NDArray<TypeVariable(T), D1> */ defined in org.jetbrains.kotlinx.multik.api
```

**Comment by devcrocod** [comment]
Ooh, that looks weird. Apparently Kotlin couldn't resolve it. Since identical signatures are written in the output, I assume that this message was duplicated.

workaround for now, I can suggest writing parameters explicitly:
```kotlin
val x = mk.arange<Float>(start = -10, stop = 10, step = 0.25)
```

Also could you separate the import and call into different cells. Because `%use multik` or `%use other_library` can execute some init code and add imports. In theory, this shouldn't have any effect, but I'm not sure.

I will check the behavior you described in myself

**Comment by devcrocod** [comment]
ok, I couldn't reproduce this bug.

Please tell us more details:
- Which version of IDEA are you using?
- Are you running this as a separate project or in the multik library?

Since a conflict may arise between the code in the notebook and the library source code. You can set up this in kotlin notebook settings:
<img width="1228" alt="image" src="https://github.com/Kotlin/multik/assets/19648120/592340e6-17cb-4d1e-a332-d3745f97a51a">

**Comment by paccuk** [comment]
- IntelliJ IDEA 2023.3.4 (Ultimate Edition)
> Build #IU-233.14475.28, built on February 13, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.7.6-arch1-1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  ide.experimental.ui=true
  Pythonid (233.14475.28)
  intellij.jupyter (233.14475.28)
  org.jetbrains.plugins.kotlin.jupyter (233.14475.9)
Kotlin: 233.14475.28-IJ
Current Desktop: KDE

- As far as I understand your question, I am running it in the multik library, not as a separate project.

![image](https://github.com/Kotlin/multik/assets/46825317/b82fad81-4f91-489d-bb37-fd2209557268)

**Comment by paccuk** [comment]
> Since a conflict may arise between the code in the notebook and the library source code. You can set up this in kotlin notebook settings:

I tried what you suggested, then restarted the kernel a few times and now it works.
Thank you for response and help.
