### ISSUE TITLE
Request for more numpy like methods.

### ISSUE THREAD

**Issue by occultus73** [Kotlin/multik#29]
Hi guys, I'm eagerly following progress you're making with the library. I've written a few more extension methods to get extra functionality out of Multik.

```
typealias RealMatrix = MultiArray<Double, D2>
typealias RealVector = MultiArray<Double, D1>

fun RealMatrix.getRowDimension() = shape[0]
fun RealMatrix.getColumnDimension() = shape[1]

// Actually in numpy you'd use array getter syntax like [:-1], but methods like drop() are intuitive to a Kotlin programmer.
fun RealMatrix.drop(number: Int): RealMatrix {
    val rows = getRowDimension()
    return this[Slice(number, rows, 1)]
}

// In numpy you can fetch multiple points by passing an array of corresponding indices for each dimension.
operator fun RealMatrix.get(indices1: IntArray, indices2: IntArray): List<Double> {
    if (indices1.size != indices2.size) error("invalid indices")
    return List(indices1.size) {
        this[indices1[it], indices2[it]]
    }
}

// Numpy allows you to do more advanced forms of matrix multiplication (not dot product) that Multik can't. 
// Here we are multiplying every row in a matrix by the numbers in a corresponding row vector of equivalent size. 
operator fun RealVector.times(matrix: RealMatrix): RealMatrix {
    val matrixRows = matrix.getRowDimension()
    val matrixColumns = matrix.getColumnDimension()
    if (size != matrixColumns) error("dimension mismatch")
    return mk.ndarray(
        List(matrixRows) {
            (this * matrix[it]).getData().toList()
        }
    )
}
```

**Comment by devcrocod** [comment]
Hi!

Now and in the near future, I do less work with the Multik library. Since we are preparing the release of a new library.
I closely follow the issues and pr. At the beginning of summer, I want to release version 0.0.2.

Regarding those extensions that you described:
1. Multik already has a `drop` for vectors. It really makes sense to write `drop` for other dimensions as well.
2. I will consider adding such a method, but most likely it will not be a `get` method. Because it can mess up the design of the API.
3. I want to find a balance between convenience and understanding of the operations being performed. Therefore, we are not yet implementing broadcasting and complex implicit operations. This will not prevent us from adding them in the future.
